import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import { preload } from "react-dom";
import Header from "../components/header";
import { AOSInit } from "../components/aos-init";
import Footer from "../components/footer/Footer";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  preload: true,
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={roboto.className}
      >
        <AOSInit />
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
