// Common animation presets
export const aosAnimations = {
  fadeInUp: () => ({
    "data-aos": "fade-up" as const,
    "data-aos-duration": "800",
    "data-aos-delay": "0",
    "data-aos-offset": "100",
    "data-aos-easing": "ease-in-out",
    "data-aos-once": true,
  }),
  fadeInDown: () => ({
    "data-aos": "fade-down" as const,
    "data-aos-duration": "800",
    "data-aos-delay": "0",
    "data-aos-offset": "100",
    "data-aos-easing": "ease-in-out",
    "data-aos-once": true,
  }),
  fadeInLeft: () => ({
    "data-aos": "fade-left" as const,
    "data-aos-duration": "800",
    "data-aos-delay": "0",
    "data-aos-offset": "100",
    "data-aos-easing": "ease-in-out",
    "data-aos-once": true,
  }),
  fadeInRight: () => ({
    "data-aos": "fade-right" as const,
    "data-aos-duration": "800",
    "data-aos-delay": "0",
    "data-aos-offset": "100",
    "data-aos-easing": "ease-in-out",
    "data-aos-once": true,
  }),
  zoomIn: () => ({
    "data-aos": "zoom-in" as const,
    "data-aos-duration": "800",
    "data-aos-delay": "0",
    "data-aos-offset": "100",
    "data-aos-easing": "ease-in-out",
    "data-aos-once": true,
  }),
  slideInUp: () => ({
    "data-aos": "slide-up" as const,
    "data-aos-duration": "800",
    "data-aos-delay": "0",
    "data-aos-offset": "100",
    "data-aos-easing": "ease-in-out",
    "data-aos-once": true,
  }),
  slideInDown: () => ({
    "data-aos": "slide-down" as const,
    "data-aos-duration": "800",
    "data-aos-delay": "0",
    "data-aos-offset": "100",
    "data-aos-easing": "ease-in-out",
    "data-aos-once": true,
  }),
  flipLeft: () => ({
    "data-aos": "flip-left" as const,
    "data-aos-duration": "800",
    "data-aos-delay": "0",
    "data-aos-offset": "100",
    "data-aos-easing": "ease-in-out",
    "data-aos-once": true,
  }),
  flipRight: () => ({
    "data-aos": "flip-right" as const,
    "data-aos-duration": "800",
    "data-aos-delay": "0",
    "data-aos-offset": "100",
    "data-aos-easing": "ease-in-out",
    "data-aos-once": true,
  }),
};
